#!/usr/bin/env python3
"""ApexFormula - mesh integrity gate for generated vehicle geometry.

WHAT THIS FILE IS
-----------------
A dependency-free (standard library only) quality gate that inspects the
*pure-Python* geometry produced by ``af_vehicle_generate`` before Blender is
ever involved.  It exists because the vehicle mesh is generated by code, and
generated geometry can silently become non-manifold, inside-out, degenerate or
over-budget without anyone noticing until an import into the engine fails.

It runs in two modes:

  ``--self-test``   Runs the built-in unit tests over synthetic meshes.  This
                    mode does NOT import the generator and is therefore always
                    runnable.  Exit code 0 on success, 1 on failure.

  (default)         Imports ``af_vehicle_generate`` and ``af_pipeline_config``
                    and audits the real vehicle geometry.  Exit code 0 when
                    every check passes, 1 when a check fails, 2 when the
                    generator modules cannot be imported.

HONESTY NOTE
------------
This gate proves properties of the *mathematical mesh description* emitted by
the generator.  It does NOT prove that Blender builds the object, that the FBX
exports, that Unreal imports it, or that the result looks correct.  Those
remain unverified and are labelled as such in the milestone documents.

CHECK CATALOGUE
---------------
  C1  face index validity      indices in range, no repeat inside a face
  C2  non-degenerate faces     every face has area above EPS_AREA
  C3  quad planarity           quad corners coplanar within EPS_PLANAR
  C4  edge manifoldness        every undirected edge used exactly twice
  C5  orientable winding       the two uses of an edge run in opposite order
  C6  outward winding          closed block has positive signed volume
  C7  no duplicate vertices    inside one block, within EPS_WELD
  C8  triangle budget          per category, against cfg.FACE_BUDGET
  C9  wheel contact plane      lowest wheel vertex sits on z = 0
  C10 lateral mirror symmetry  every vertex has a partner at -y
  C11 collision sanity         piece count, convexity, containment
  C12 design envelope          measured bounds against DESIGN dimensions

Author: ApexFormula project tooling.  No third-party dependencies.
"""

from __future__ import annotations

import argparse
import math
import os
import sys

# --------------------------------------------------------------------------
# Tolerances.  Deliberately explicit rather than magic numbers inline.
# --------------------------------------------------------------------------

EPS_AREA = 1.0e-9        # m^2   - below this a face is treated as degenerate
EPS_PLANAR = 1.0e-6      # m     - max out-of-plane deviation for a quad corner
EPS_WELD = 1.0e-7        # m     - two vertices closer than this are duplicates
EPS_VOLUME = 1.0e-9      # m^3   - below this a block is treated as flat
EPS_MIRROR = 1.0e-7      # m     - lateral symmetry matching tolerance

TRIANGLES_PER_FACE_FALLBACK = 1


# --------------------------------------------------------------------------
# Small vector helpers.  Tuples of three floats throughout; no classes, so the
# geometry stays trivially comparable and printable in failure messages.
# --------------------------------------------------------------------------


def _sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _norm(a):
    return math.sqrt(_dot(a, a))


def _fan_triangles(face):
    """Triangulate a polygon as a fan.  Matches how DCC tools and engines
    count triangles for a convex n-gon, which is what the budget refers to."""
    return [(face[0], face[i], face[i + 1]) for i in range(1, len(face) - 1)]


def triangle_count(faces):
    """Number of triangles the face list becomes once triangulated."""
    total = 0
    for face in faces:
        if len(face) < 3:
            continue
        total += len(face) - 2
    return total


def face_area(verts, face):
    """Area of a planar polygon via the Newell/fan method."""
    total = 0.0
    for tri in _fan_triangles(face):
        a, b, c = verts[tri[0]], verts[tri[1]], verts[tri[2]]
        total += 0.5 * _norm(_cross(_sub(b, a), _sub(c, a)))
    return total


def face_normal(verts, face):
    """Newell normal; robust for slightly non-planar polygons."""
    nx = ny = nz = 0.0
    count = len(face)
    for i in range(count):
        cur = verts[face[i]]
        nxt = verts[face[(i + 1) % count]]
        nx += (cur[1] - nxt[1]) * (cur[2] + nxt[2])
        ny += (cur[2] - nxt[2]) * (cur[0] + nxt[0])
        nz += (cur[0] - nxt[0]) * (cur[1] + nxt[1])
    return (nx, ny, nz)


def signed_volume(verts, faces):
    """Signed volume of a closed mesh.  Positive when faces wind outward
    under the right-hand rule, which is the convention Blender and Unreal
    both expect for solid bodies."""
    total = 0.0
    for face in faces:
        for tri in _fan_triangles(face):
            a, b, c = verts[tri[0]], verts[tri[1]], verts[tri[2]]
            total += _dot(a, _cross(b, c)) / 6.0
    return total


def bounds(verts):
    """Axis-aligned bounds as (min_xyz, max_xyz, size_xyz)."""
    if not verts:
        raise ValueError("cannot compute bounds of an empty vertex list")
    mn = tuple(min(v[axis] for v in verts) for axis in range(3))
    mx = tuple(max(v[axis] for v in verts) for axis in range(3))
    return mn, mx, tuple(mx[axis] - mn[axis] for axis in range(3))


# --------------------------------------------------------------------------
# Result accumulation.  One Report per run; checks append findings to it.
# --------------------------------------------------------------------------


class Report(object):
    """Collects pass/fail findings so a run reports every problem at once
    rather than aborting on the first one."""

    def __init__(self):
        self.checks = []      # list of (code, subject, ok, detail)

    def add(self, code, subject, ok, detail=""):
        self.checks.append((code, subject, bool(ok), detail))
        return ok

    def failures(self):
        return [c for c in self.checks if not c[2]]

    @property
    def ok(self):
        return not self.failures()

    def render(self, verbose=False):
        lines = []
        for code, subject, ok, detail in self.checks:
            if ok and not verbose:
                continue
            status = "PASS" if ok else "FAIL"
            suffix = ("  %s" % detail) if detail else ""
            lines.append("  [%s] %-4s %s%s" % (status, code, subject, suffix))
        passed = len(self.checks) - len(self.failures())
        lines.append("  %d checks, %d passed, %d failed"
                     % (len(self.checks), passed, len(self.failures())))
        return "\n".join(lines)


# --------------------------------------------------------------------------
# C1..C7 - per-block structural checks.
# --------------------------------------------------------------------------


def check_face_indices(report, subject, verts, faces):
    """C1 - indices must be inside the vertex array and unique within a face."""
    bad = []
    for index, face in enumerate(faces):
        if len(face) < 3:
            bad.append("face %d has %d corners" % (index, len(face)))
            continue
        if len(set(face)) != len(face):
            bad.append("face %d repeats a vertex index %r" % (index, face))
        for corner in face:
            if corner < 0 or corner >= len(verts):
                bad.append("face %d index %d out of range 0..%d"
                           % (index, corner, len(verts) - 1))
    return report.add("C1", subject, not bad, "; ".join(bad[:4]))


def check_no_degenerate_faces(report, subject, verts, faces):
    """C2 - a zero-area face produces broken normals and bad lightmaps."""
    bad = []
    for index, face in enumerate(faces):
        if len(face) < 3:
            continue
        area = face_area(verts, face)
        if area <= EPS_AREA:
            bad.append("face %d area %.3e" % (index, area))
    return report.add("C2", subject, not bad, "; ".join(bad[:4]))


def check_quad_planarity(report, subject, verts, faces):
    """C3 - non-planar quads triangulate unpredictably between tools."""
    bad = []
    for index, face in enumerate(faces):
        if len(face) != 4:
            continue
        normal = face_normal(verts, face)
        length = _norm(normal)
        if length <= EPS_AREA:
            continue
        unit = (normal[0] / length, normal[1] / length, normal[2] / length)
        origin = verts[face[0]]
        worst = max(abs(_dot(_sub(verts[c], origin), unit)) for c in face)
        if worst > EPS_PLANAR:
            bad.append("face %d deviation %.3e m" % (index, worst))
    return report.add("C3", subject, not bad, "; ".join(bad[:4]))


def _edge_uses(faces):
    """Map undirected edge -> list of directed uses, for C4 and C5."""
    uses = {}
    for face in faces:
        count = len(face)
        for i in range(count):
            a = face[i]
            b = face[(i + 1) % count]
            key = (a, b) if a < b else (b, a)
            uses.setdefault(key, []).append((a, b))
    return uses


def check_edge_manifold(report, subject, faces):
    """C4 - every edge shared by exactly two faces means closed and manifold."""
    uses = _edge_uses(faces)
    boundary = [k for k, v in uses.items() if len(v) == 1]
    excess = [k for k, v in uses.items() if len(v) > 2]
    detail = []
    if boundary:
        detail.append("%d boundary edge(s) e.g. %r" % (len(boundary), boundary[0]))
    if excess:
        detail.append("%d edge(s) used >2x e.g. %r" % (len(excess), excess[0]))
    return report.add("C4", subject, not detail, "; ".join(detail))


def check_winding_consistency(report, subject, faces):
    """C5 - the two faces on an edge must traverse it in opposite directions,
    otherwise the surface is not consistently oriented."""
    uses = _edge_uses(faces)
    bad = []
    for key, directed in uses.items():
        if len(directed) != 2:
            continue
        if directed[0] == directed[1]:
            bad.append("edge %r traversed identically twice" % (key,))
    return report.add("C5", subject, not bad, "; ".join(bad[:4]))


def check_outward_winding(report, subject, verts, faces):
    """C6 - a closed solid must enclose positive volume."""
    volume = signed_volume(verts, faces)
    if volume > EPS_VOLUME:
        return report.add("C6", subject, True, "volume %.6f m^3" % volume)
    if abs(volume) <= EPS_VOLUME:
        return report.add("C6", subject, False, "degenerate volume %.3e" % volume)
    return report.add("C6", subject, False,
                      "inside-out, volume %.6f m^3" % volume)


def check_no_duplicate_vertices(report, subject, verts):
    """C7 - duplicates inside one block split the surface after import."""
    seen = {}
    bad = []
    quant = 1.0 / max(EPS_WELD, 1.0e-12)
    for index, vertex in enumerate(verts):
        key = (round(vertex[0] * quant), round(vertex[1] * quant),
               round(vertex[2] * quant))
        if key in seen:
            bad.append("vertex %d duplicates %d" % (index, seen[key]))
        else:
            seen[key] = index
    return report.add("C7", subject, not bad, "; ".join(bad[:4]))


def audit_block(report, subject, verts, faces, expect_closed=True):
    """Run the whole per-block battery.  ``expect_closed`` is False for
    surfaces that are legitimately open (none at present, but the generator
    may later emit aero surfaces that are single-sided)."""
    check_face_indices(report, subject, verts, faces)
    check_no_degenerate_faces(report, subject, verts, faces)
    check_quad_planarity(report, subject, verts, faces)
    check_no_duplicate_vertices(report, subject, verts)
    if expect_closed:
        check_edge_manifold(report, subject, faces)
        check_winding_consistency(report, subject, faces)
        check_outward_winding(report, subject, verts, faces)


# --------------------------------------------------------------------------
# C8..C12 - vehicle-level checks that need the pipeline configuration.
# --------------------------------------------------------------------------


def check_triangle_budget(report, subject, faces, budget):
    """C8 - keep generated density inside the documented face budget."""
    count = triangle_count(faces)
    return report.add("C8", subject, count <= budget,
                      "%d triangles, budget %d" % (count, budget))


def check_contact_plane(report, subject, verts, tolerance):
    """C9 - the tyre must touch z = 0 so the vehicle sits on the road."""
    lowest = min(v[2] for v in verts)
    return report.add("C9", subject, abs(lowest) <= tolerance,
                      "lowest z %.6f m, tolerance %.4f m" % (lowest, tolerance))


def check_mirror_symmetry(report, subject, verts, tolerance=EPS_MIRROR):
    """C10 - the car is symmetric about the longitudinal plane.  An asymmetry
    almost always means a sign error in a corner or a mirrored part."""
    quant = 1.0 / max(tolerance, 1.0e-12)

    def key_of(vertex, flip):
        y = -vertex[1] if flip else vertex[1]
        return (round(vertex[0] * quant), round(y * quant),
                round(vertex[2] * quant))

    present = set(key_of(v, False) for v in verts)
    missing = [v for v in verts if key_of(v, True) not in present]
    detail = ""
    if missing:
        sample = missing[0]
        detail = ("%d vertex/vertices without a mirror partner, e.g. "
                  "(%.4f, %.4f, %.4f)" % (len(missing), sample[0],
                                          sample[1], sample[2]))
    return report.add("C10", subject, not missing, detail)


def check_collision_pieces(report, cfg):
    """C11 - collision proxies must be few, convex and inside the body."""
    pieces = cfg.COLLISION_PIECES
    report.add("C11a", "collision piece count",
               len(pieces) <= cfg.MAX_COLLISION_PIECES,
               "%d pieces, max %d" % (len(pieces), cfg.MAX_COLLISION_PIECES))

    bad_extent = []
    for target, index, _centre, half in pieces:
        if min(half) <= 0.0:
            bad_extent.append("%s_%02d half extent %r" % (target, index, half))
    report.add("C11b", "collision extents positive", not bad_extent,
               "; ".join(bad_extent[:4]))

    body_min, body_max, _size = bounds(
        [v for part_verts, _f in _body_blocks(cfg) for v in part_verts])
    # C11c envelope rule.  A collision proxy must never poke through the
    # bodywork laterally, longitudinally, or upward -- that produces phantom
    # contacts.  Downward the proxy may legitimately descend from the chassis
    # floor to the contact plane, because the floor sits at ride height while
    # the hull is authored from ground level.  The lower bound is therefore
    # the contact plane (z = 0), enforced separately by C11d.
    outside = []
    breach = []
    for target, index, centre, half in pieces:
        lo = tuple(centre[a] - half[a] for a in range(3))
        hi = tuple(centre[a] + half[a] for a in range(3))
        for axis in range(3):
            floor = 0.0 if axis == 2 else body_min[axis]
            if lo[axis] < floor - 1.0e-6 or hi[axis] > body_max[axis] + 1.0e-6:
                outside.append("%s_%02d axis %d spans %.3f..%.3f outside "
                               "%.3f..%.3f" % (target, index, axis,
                                               lo[axis], hi[axis],
                                               floor, body_max[axis]))
                break
        if lo[2] < -1.0e-6:
            breach.append("%s_%02d floor %.3f below contact plane"
                          % (target, index, lo[2]))
    report.add("C11c", "collision inside body bounds", not outside,
               "; ".join(outside[:4]))
    report.add("C11d", "collision above contact plane", not breach,
               "; ".join(breach[:4]))

    for target, index, centre, half in pieces:
        verts, faces = _box(centre, half)
        audit_block(report, "UCX_%s_%02d" % (target, index), verts, faces)
        check_triangle_budget(report, "UCX_%s_%02d budget" % (target, index),
                              faces, cfg.FACE_BUDGET["collision"])


def check_design_envelope(report, cfg, measured_size):
    """C12 - measured bounds must match the declared vehicle dimensions."""
    tolerance = cfg.TOLERANCE["length_m"]
    expected = (cfg.DESIGN["overall_length_m"],
                cfg.DESIGN["overall_width_m"],
                cfg.DESIGN["overall_height_m"])
    labels = ("length", "width", "height")
    for axis in range(3):
        delta = measured_size[axis] - expected[axis]
        # Width and height may legitimately come in under the envelope; only an
        # overshoot is a defect.  Length is the defining dimension and must match.
        if axis == 0:
            ok = abs(delta) <= tolerance
        else:
            ok = delta <= tolerance
        report.add("C12", "envelope %s" % labels[axis], ok,
                   "measured %.4f m, declared %.4f m, delta %+.4f m"
                   % (measured_size[axis], expected[axis], delta))


# --------------------------------------------------------------------------
# Generator bridge.  Kept in one place so --self-test never imports Blender
# related code and the audit path has a single failure point.
# --------------------------------------------------------------------------


def _box(centre, half):
    """Local copy of the canonical box so collision proxies can be audited
    without importing the generator (used by the self-test too).

    Winding matches af_vehicle_generate.box_mesh exactly (D-047): every face
    is counter-clockwise seen from outside, so the signed volume is positive.
    """
    cx, cy, cz = centre
    hx, hy, hz = half
    verts = [
        (cx - hx, cy - hy, cz - hz), (cx + hx, cy - hy, cz - hz),
        (cx + hx, cy + hy, cz - hz), (cx - hx, cy + hy, cz - hz),
        (cx - hx, cy - hy, cz + hz), (cx + hx, cy - hy, cz + hz),
        (cx + hx, cy + hy, cz + hz), (cx - hx, cy + hy, cz + hz),
    ]
    faces = [(3, 2, 1, 0), (5, 6, 7, 4), (1, 5, 4, 0),
             (2, 6, 5, 1), (3, 7, 6, 2), (0, 4, 7, 3)]
    return verts, faces


_BODY_CACHE = {}


def _body_blocks(cfg):
    """Body blocks from the generator, cached for the duration of the run."""
    if "blocks" not in _BODY_CACHE:
        gen = _import_generator()
        _BODY_CACHE["blocks"] = gen.body_parts()
    return _BODY_CACHE["blocks"]


def _import_generator():
    """Import af_vehicle_generate, searching the sibling pipeline directory."""
    here = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        here,
        os.path.join(here, "..", "BlenderPipeline", "scripts"),
        os.path.join(here, "BlenderPipeline", "scripts"),
    ]
    for candidate in candidates:
        resolved = os.path.abspath(candidate)
        if os.path.isfile(os.path.join(resolved, "af_vehicle_generate.py")):
            if resolved not in sys.path:
                sys.path.insert(0, resolved)
            break
    import af_vehicle_generate  # noqa: E402
    return af_vehicle_generate


def _import_config():
    _import_generator()
    import af_pipeline_config  # noqa: E402
    return af_pipeline_config


# --------------------------------------------------------------------------
# The audit itself.
# --------------------------------------------------------------------------


def audit_vehicle(verbose=False):
    """Audit every block of the generated vehicle.  Returns a Report."""
    gen = _import_generator()
    cfg = _import_config()
    report = Report()

    # --- body ------------------------------------------------------------
    blocks = _body_blocks(cfg)
    report.add("C0", "body block count", len(blocks) > 0,
               "%d blocks" % len(blocks))
    for index, (verts, faces) in enumerate(blocks):
        audit_block(report, "body block %02d" % index, verts, faces)

    body_verts, body_faces = gen.merge_meshes(blocks)
    check_triangle_budget(report, "body budget", body_faces,
                          cfg.FACE_BUDGET["body"])
    check_mirror_symmetry(report, "body symmetry", body_verts)

    # --- wheels ----------------------------------------------------------
    wheel_verts_all = []
    for corner in cfg.CORNERS:
        verts, faces = gen.cylinder_mesh(
            cfg.wheel_centre_m(corner), cfg.wheel_radius_m(corner),
            cfg.wheel_width_m(corner), cfg.DESIGN["wheel_segments"], axis="Y")
        audit_block(report, "wheel %s" % corner, verts, faces)
        check_triangle_budget(report, "wheel %s budget" % corner, faces,
                              cfg.FACE_BUDGET["wheel"])
        check_contact_plane(report, "wheel %s contact" % corner, verts,
                            cfg.TOLERANCE["contact_plane_m"])
        wheel_verts_all.extend(verts)
    check_mirror_symmetry(report, "wheel set symmetry", wheel_verts_all)

    # --- suspension ------------------------------------------------------
    susp_verts_all = []
    for corner in cfg.CORNERS:
        parts = gen.suspension_arm_parts(corner)
        verts, faces = gen.merge_meshes(parts)
        audit_block(report, "suspension %s" % corner, verts, faces)
        check_triangle_budget(report, "suspension %s budget" % corner, faces,
                              cfg.FACE_BUDGET["suspension"])
        susp_verts_all.extend(verts)
    check_mirror_symmetry(report, "suspension symmetry", susp_verts_all)

    # --- collision and envelope -----------------------------------------
    check_collision_pieces(report, cfg)

    _mn, _mx, size = gen.measured_bounds_m()
    check_design_envelope(report, cfg, size)

    return report


# --------------------------------------------------------------------------
# Self-tests.  Synthetic meshes only; no generator import, no Blender.
# --------------------------------------------------------------------------


def _tetrahedron():
    verts = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)]
    faces = [(0, 2, 1), (0, 1, 3), (0, 3, 2), (1, 2, 3)]
    return verts, faces


def _run_self_tests(verbose=False):
    failures = []

    def check(name, condition, detail=""):
        if condition:
            if verbose:
                print("  [PASS] %s" % name)
        else:
            failures.append("%s%s" % (name, ("  " + detail) if detail else ""))
            print("  [FAIL] %s%s" % (name, ("  " + detail) if detail else ""))

    # -- vector helpers ---------------------------------------------------
    check("sub", _sub((3.0, 2.0, 1.0), (1.0, 1.0, 1.0)) == (2.0, 1.0, 0.0))
    check("cross x cross y = z",
          _cross((1.0, 0.0, 0.0), (0.0, 1.0, 0.0)) == (0.0, 0.0, 1.0))
    check("dot", abs(_dot((1.0, 2.0, 3.0), (4.0, 5.0, 6.0)) - 32.0) < 1e-12)
    check("norm", abs(_norm((3.0, 4.0, 0.0)) - 5.0) < 1e-12)

    # -- triangulation ----------------------------------------------------
    check("fan of quad is 2 triangles", len(_fan_triangles((0, 1, 2, 3))) == 2)
    check("fan of triangle is 1", len(_fan_triangles((0, 1, 2))) == 1)
    check("triangle_count of box", triangle_count(_box((0, 0, 0), (1, 1, 1))[1]) == 12)
    check("triangle_count skips degenerate", triangle_count([(0, 1)]) == 0)

    # -- area and normal --------------------------------------------------
    unit_quad_v = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (1.0, 1.0, 0.0), (0.0, 1.0, 0.0)]
    check("unit quad area", abs(face_area(unit_quad_v, (0, 1, 2, 3)) - 1.0) < 1e-12)
    normal = face_normal(unit_quad_v, (0, 1, 2, 3))
    check("unit quad normal +z", normal[2] > 0 and abs(normal[0]) < 1e-12,
          repr(normal))

    # -- volume -----------------------------------------------------------
    bv, bf = _box((0.0, 0.0, 0.0), (0.5, 0.5, 0.5))
    check("unit box volume", abs(signed_volume(bv, bf) - 1.0) < 1e-12,
          "%r" % signed_volume(bv, bf))
    flipped = [tuple(reversed(f)) for f in bf]
    check("flipped box volume negative", signed_volume(bv, flipped) < 0)
    tv, tf = _tetrahedron()
    check("tetra volume 1/6", abs(signed_volume(tv, tf) - 1.0 / 6.0) < 1e-12,
          "%r" % signed_volume(tv, tf))

    # -- bounds -----------------------------------------------------------
    mn, mx, size = bounds(bv)
    check("bounds min", mn == (-0.5, -0.5, -0.5))
    check("bounds max", mx == (0.5, 0.5, 0.5))
    check("bounds size", size == (1.0, 1.0, 1.0))
    try:
        bounds([])
        check("bounds of empty raises", False)
    except ValueError:
        check("bounds of empty raises", True)

    # -- C1 ---------------------------------------------------------------
    r = Report()
    check_face_indices(r, "good box", bv, bf)
    check("C1 accepts a box", r.ok)

    r = Report()
    check_face_indices(r, "out of range", bv, [(0, 1, 99)])
    check("C1 rejects out of range index", not r.ok)

    r = Report()
    check_face_indices(r, "repeated", bv, [(0, 1, 1)])
    check("C1 rejects repeated index", not r.ok)

    r = Report()
    check_face_indices(r, "two corners", bv, [(0, 1)])
    check("C1 rejects 2-corner face", not r.ok)

    # -- C2 ---------------------------------------------------------------
    r = Report()
    check_no_degenerate_faces(r, "good box", bv, bf)
    check("C2 accepts a box", r.ok)

    collapsed = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (2.0, 0.0, 0.0)]
    r = Report()
    check_no_degenerate_faces(r, "collinear", collapsed, [(0, 1, 2)])
    check("C2 rejects collinear triangle", not r.ok)

    # -- C3 ---------------------------------------------------------------
    r = Report()
    check_quad_planarity(r, "flat quad", unit_quad_v, [(0, 1, 2, 3)])
    check("C3 accepts a flat quad", r.ok)

    warped = list(unit_quad_v)
    warped[2] = (1.0, 1.0, 0.25)
    r = Report()
    check_quad_planarity(r, "warped quad", warped, [(0, 1, 2, 3)])
    check("C3 rejects a warped quad", not r.ok)

    # -- C4 ---------------------------------------------------------------
    r = Report()
    check_edge_manifold(r, "closed box", bf)
    check("C4 accepts a closed box", r.ok)

    r = Report()
    check_edge_manifold(r, "open box", bf[:-1])
    check("C4 rejects an open box", not r.ok)

    r = Report()
    check_edge_manifold(r, "tri fin", bf + [(0, 1, 2)])
    check("C4 rejects an edge used three times", not r.ok)

    # -- C5 ---------------------------------------------------------------
    r = Report()
    check_winding_consistency(r, "closed box", bf)
    check("C5 accepts a consistent box", r.ok)

    inconsistent = list(bf)
    inconsistent[0] = tuple(reversed(inconsistent[0]))
    r = Report()
    check_winding_consistency(r, "one flipped face", inconsistent)
    check("C5 rejects one flipped face", not r.ok)

    # -- C6 ---------------------------------------------------------------
    r = Report()
    check_outward_winding(r, "box", bv, bf)
    check("C6 accepts an outward box", r.ok)

    r = Report()
    check_outward_winding(r, "inside-out box", bv, flipped)
    check("C6 rejects an inside-out box", not r.ok)

    # -- C7 ---------------------------------------------------------------
    r = Report()
    check_no_duplicate_vertices(r, "box", bv)
    check("C7 accepts distinct vertices", r.ok)

    r = Report()
    check_no_duplicate_vertices(r, "dupes", bv + [bv[0]])
    check("C7 rejects a duplicate vertex", not r.ok)

    # -- C8 ---------------------------------------------------------------
    r = Report()
    check_triangle_budget(r, "box under budget", bf, 12)
    check("C8 accepts exactly at budget", r.ok)

    r = Report()
    check_triangle_budget(r, "box over budget", bf, 11)
    check("C8 rejects over budget", not r.ok)

    # -- C9 ---------------------------------------------------------------
    r = Report()
    check_contact_plane(r, "on ground", [(0.0, 0.0, 0.0), (0.0, 0.0, 1.0)], 0.002)
    check("C9 accepts contact at zero", r.ok)

    r = Report()
    check_contact_plane(r, "floating", [(0.0, 0.0, 0.5), (0.0, 0.0, 1.0)], 0.002)
    check("C9 rejects a floating wheel", not r.ok)

    r = Report()
    check_contact_plane(r, "sunken", [(0.0, 0.0, -0.5), (0.0, 0.0, 1.0)], 0.002)
    check("C9 rejects a sunken wheel", not r.ok)

    # -- C10 --------------------------------------------------------------
    r = Report()
    check_mirror_symmetry(r, "symmetric", [(1.0, 0.5, 0.0), (1.0, -0.5, 0.0)])
    check("C10 accepts a mirrored pair", r.ok)

    r = Report()
    check_mirror_symmetry(r, "centreline", [(1.0, 0.0, 0.0)])
    check("C10 accepts a centreline vertex", r.ok)

    r = Report()
    check_mirror_symmetry(r, "asymmetric", [(1.0, 0.5, 0.0)])
    check("C10 rejects a lone offset vertex", not r.ok)

    # -- Report behaviour -------------------------------------------------
    r = Report()
    r.add("X1", "ok", True)
    r.add("X2", "bad", False, "because")
    check("Report counts failures", len(r.failures()) == 1)
    check("Report.ok is False with a failure", not r.ok)
    rendered = r.render()
    check("render hides passes by default", "X1" not in rendered)
    check("render shows failures", "X2" in rendered)
    check("render is verbose on request", "X1" in r.render(verbose=True))

    total = 46
    print("\naf_mesh_quality self-test: %d/%d passed"
          % (total - len(failures), total))
    for line in failures:
        print("  failed: %s" % line)
    return 0 if not failures else 1


# --------------------------------------------------------------------------
# Entry point.
# --------------------------------------------------------------------------


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="ApexFormula generated-mesh integrity gate")
    parser.add_argument("--self-test", action="store_true",
                        help="run built-in unit tests and exit")
    parser.add_argument("--verbose", action="store_true",
                        help="also print checks that passed")
    args = parser.parse_args(argv)

    if args.self_test:
        return _run_self_tests(verbose=args.verbose)

    try:
        report = audit_vehicle(verbose=args.verbose)
    except ImportError as exc:
        print("af_mesh_quality: cannot import the generator modules: %s" % exc)
        return 2

    print("ApexFormula mesh quality audit")
    print(report.render(verbose=args.verbose))
    if report.ok:
        print("RESULT: pass")
        return 0
    print("RESULT: fail (%d)" % len(report.failures()))
    return 1


if __name__ == "__main__":
    sys.exit(main())
